[project]
name = "python-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "geopandas>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "osmnx>=2.0.7",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
]
